[build-system]
requires = ["setuptools>=65.0", "wheel >=0.37"]

[project]
name = "python_project_template"
authors = [{name = "Anthony Corletti", email = "python_project_template@example.com"}]
dynamic = ["version", "readme"]
requires-python = ">=3.10"
dependencies = []

[project.optional-dependencies]
test = [
    "pytest >=6.2.5",
    "coverage >=6.1.1",
    "pytest-cov >=3.0.0",
]
dev = [
    "flake8 >=3.9.2",
    "mypy >=0.910",
    "black >=21.10b0",
    "isort >=5.9.3",
    "autoflake >=1.4",
    "flake8-docstrings >=1.6.0",
    "pre-commit >=2.17.0",
]

[project.urls]
Documentation = "https://www.github.com/anthonycorletti/python_project_template"

[tool.setuptools]
py-modules = ["python_project_template"]

[tool.setuptools.dynamic]
version = {attr = "python_project_template.__version__"}
readme = {file = ["README.md"]}

[tool.isort]
profile = "black"
